"""secrets e grupos paralelos

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-13 20:29:46.529123
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secrets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets')),
    sa.UniqueConstraint('project', 'name', name=op.f('uq_secrets_project_name'))
    )
    with op.batch_alter_table('step_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverte a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_runs', schema=None) as batch_op:
        batch_op.drop_column('group_name')

    op.drop_table('secrets')
    # ### end Alembic commands ###
